version: '2'

services:
  redis:
    image: 'docker.io/bitnami/redis:6.2-debian-10'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  ses:
    image: jdelibas/aws-ses-local
    hostname: ses-local
    container_name: ses-local
    ports:
        - "8120:8002"
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"

volumes:
  redis_data:
    driver: local
